### ISSUE TITLE
 Clarification on Task Expectations

### ISSUE THREAD

**Issue by Hithesh2022** [GitHub-Octernships/Shuffle-Frontend-Developer-Software-Engineering#4]
@jaygohil-cyber  @ashwinexe  i have updated code to prevent duplicate contents i have a doubt 
that i should only prevent duplicate content whenever new words are appended  or must  also enable overwriting as when i try to overwrite the file it didnt worked and new word appended with old one but prevented duplicate contents with my updated code

Also can you explain in detail how to submit Assignment it is mentioned that submit in <repository>/assignment_files. so should i assume to upload on this repo Assignment 1 branch ???

**Comment by jaygohil-cyber** [comment]
Hey @Hithesh2022, check this out:

https://github.com/Shuffle/Shuffle/issues/1176#issuecomment-1793512027
